### ISSUE TITLE
Add plus sign to dragged frame when option-dragging

### ISSUE THREAD

**Issue by mkolling** [k-pet-group/Strype#358]
Add a little (+) symbol (see MacOS Finder) to the dragged frame preview when duplicating a frame by dragging (Option-drag).

**Comment by PwtKCL** [comment]
As discussed in meeting, we will add the "+" symbol at the destination frame cursor rather than at the image (easier to implement).
The "+" symbol is a green disc with a clear white "+" inside, like in macOS.

(Note: we discussed having the mouse pointer changed to the CSS supported "copy" cursor, but it's not very clear to see in Chrome at least - and we also discussed having our own cursor, but if we do it for this case, we may need to do for all cursors as otherwise there will be incoherence...)
